### PR TITLE
Changes to pageobjectlibrary

### PR DESCRIPTION
**Pull request by dedie**
Have made changes to work with python 3 and 2.6 or greater
Changed to use SeleniumLibrary
Some tidying up to make flake8 happier
Tested by installing on both Python 2.7.15, Python 3.6.5 and robotframework-seleniumlibrary-3.1.1

### CODE REVIEW

**Comment by GLMeece** [comment]
Giving this P.R. a 👍 as the newer Selenium library has better browser support going forward.

**Comment by ablatov** [comment]
@GLMeece @dedie Hi guys! I would like to use your library now on my project. The main pain is that for now it does not support Python 3+ installation. I see that this pull request should fix it. How much time will the merge process take?

**Comment by GLMeece** [comment]
@ablatov - that's up to @boakley as he is the owner of this project.

**Comment by ablatov** [comment]
Thanks!
21 авг. 2018 г. 19:28 пользователь "Bryan Oakley" <notifications@github.com>
написал:

**Pull request merged**
